local sign = ngx.var.arg_sign
local timestamp = ngx.var.arg_timestamp
local theTimestampNumber = tonumber(timestamp);
local session = ngx.var.arg_session
local nowTime = os.time()

-- Check the timestamp is valid.
-- The params passed by the user.
function checkParams()
    if sign == nil or timestamp == nil or theTimestampNumber == nil then
        return false
    end

    return true
end

-- Compute the signature of request url.
function computeSign()
    -- The secret passed by the front end cannot be defined by constants, but generated by certain function rules to prevent the client code from being reversely parsed.
    local secret = "ngxway"

    -- sign = md5(md5("timestamp_secret_timestamp"))
    -- sign = Take the first [10, 25] bits of sign.
    local k = string.format("%s_%s_%s", timestamp, secret, timestamp)
    local length = theTimestampNumber%16 + 10
    local md5K = ngx.md5(k)
    return string.sub(md5K, 0, length)
end

-- Check the url signature is right.
function checkSign()
    -- Generate real signatures.
    local realSign = computeSign()

    -- Check whether the signatures are consistent.
    if realSign ~= sign then
        return false
    end

    return true
end

-- Check the timestamp is valid.
function checkTimestamp()
    -- If the timestamp difference is within 1 hour, it is considered a normal request, otherwise it is considered a malicious request.
    if math.abs(nowTime - theTimestampNumber) > 3600 then
        return false
    end

    return true
end

-- If the session is not empty, check whether the request signature is legal.
if session == "" or session == nil then
    -- Check whether the parameters are normal.
    if checkParams() == false then
        ngx.log(ngx.NOTICE, 'check params failed')
        return ngx.say('{"dm_error":4031,"error_msg":"check sign failed"}')
    end

    -- Prevent user recall attacks.
    -- So if the timestamp differs greatly from the server, the request is rejected directly.
    if checkTimestamp() == false then
        ngx.log(ngx.NOTICE, 'check timestamp failed')
        return ngx.say('{"dm_error":4031,"error_msg":"check sign failed"}')
    end

    -- Prevent users from swiping the api.
    -- So if the signature verification fails, the request is rejected directly.
    if checkSign() == false then
        ngx.log(ngx.NOTICE, 'check sign failed')
        return ngx.say('{"dm_error":4031,"error_msg":"check sign failed"}')
    end
end
